stages:
  - build
  - test
  - deploy

variables:
  PYTHON_VERSION: "3.9"
  IMAGE_NAME: "diamond-price-model"

before_script:
  - python --version
  - pip install --upgrade pip
  - pip install -r requirements.txt

build:
  stage: build
  script:
    - echo "Building Docker image..."
    - docker build -t $IMAGE_NAME .

deploy:
  stage: deploy
  script:
    - echo "Deploying application..."
    - ./deploy_script.sh