apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp2
  template:
    metadata:
      labels:
        app: myapp2
    spec:
      containers:
      - name: myapp2
        image: rudy12/myapp2:v1
        env:
        - name: URL
          value: "http://myapp-service:5000"